// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsT-usOhzg_cigNmXGLl388HH_zrwiQPA',
    appId: '1:596117690028:android:c7ba7202aec6738095f109',
    messagingSenderId: '596117690028',
    projectId: 'lets-chat-ea950',
    storageBucket: 'lets-chat-ea950.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPNdDcdxIYNPrO016zIdDK5Q-imKH2EQE',
    appId: '1:596117690028:ios:9e88c31fda8ad5b495f109',
    messagingSenderId: '596117690028',
    projectId: 'lets-chat-ea950',
    storageBucket: 'lets-chat-ea950.appspot.com',
    androidClientId: '596117690028-a7mp7t9f8n41q3fl2f68h6kl81vipl5u.apps.googleusercontent.com',
    iosClientId: '596117690028-9ti9vl0pm16nki5rmka57cle8upj8d6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.letschat',
  );
}
